### ISSUE TITLE
[NPE] IabHelper.queryPurchases

### ISSUE THREAD

**Issue by vbarthel-fr** [tvbarthel/SimpleWeatherForecast#4]
java.lang.NullPointerException
in com.android.vending.billing.util.IabHelper.queryPurchases

java.lang.NullPointerException
at com.android.vending.billing.util.IabHelper.queryPurchases(IabHelper.java:836)
at com.android.vending.billing.util.IabHelper.queryInventory(IabHelper.java:558)
at com.android.vending.billing.util.IabHelper.queryInventory(IabHelper.java:522)
at com.android.vending.billing.util.IabHelper$2.run(IabHelper.java:617)
at java.lang.Thread.run(Thread.java:841)

**Comment by vbarthel-fr** [comment]
7bcb090b9f75921fb693f160949676b1bda3921f & 4923c011c24610e058595aa08fca706dcb059830
